language: c

before_install:
    - sudo apt-add-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes valac libglib2.0-dev intltool libappindicator3-dev libgtk-3-dev libpeas-dev libunity-dev libxtst-dev libzeitgeist-2.0-dev python xvfb zeitgeist at-spi2-core

script:
    - ./waf configure --enable-unityscope
    - ./waf build --testcmd='%s --integration'
